apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:0.2.3
        args:
        - "-text=API is running"
        ports:
        - containerPort: 5678
        # TODO: Add readiness and liveness probes
