apiVersion: v1
kind: Pod
metadata:
  name: database
  namespace: monitoring
spec:
  containers:
  - name: postgres
    image: postgres:14-alpine
    env:
    - name: POSTGRES_PASSWORD
      value: testpass
    ports:
    - containerPort: 5432
    startupProbe:
      # TODO: Add TCP socket startup probe
    livenessProbe:
      # TODO: Add exec command liveness probe
    readinessProbe:
      # TODO: Add exec command readiness probe
