apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: monitoring
spec:
  containers:
  - name: nginx
    image: nginx:1.21-alpine
    ports:
    - containerPort: 80
    livenessProbe:
      # TODO: Add HTTP GET liveness probe configuration
    readinessProbe:
      # TODO: Add HTTP GET readiness probe configuration
