apiVersion: v1
kind: Service
metadata:
  name: simple-node-server-service
spec:
  type: NodePort
  selector:
    app: simple-node-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
      