apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-blue
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      # TODO: Add appropriate labels for blue version
  template:
    metadata:
      labels:
        # TODO: Add appropriate labels for blue version
    spec:
      containers:
      - name: nginx
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
