apiVersion: v1
kind: Service
metadata:
  name: public-service
  labels:
    app: public-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    role: blue
  type: LoadBalancer
