apiVersion: v1
kind: Pod
metadata:
  name: web-app
  namespace: webapp
spec:
  containers:
  - name: nginx
    image: nginx:1.21-alpine
    env:
    # TODO: Add environment variables from app-config ConfigMap
    # TODO: Add DB_USERNAME from db-credentials Secret
    # TODO: Add DB_PASSWORD from db-credentials Secret
    volumeMounts:
    # TODO: Add volume mount for db-config ConfigMap
  volumes:
  # TODO: Add volume definition for db-config ConfigMap
