apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-10-11T12:26:31Z"
  labels:
    app: nginx-deploy
  name: nginx-svc
  namespace: default
  resourceVersion: "296298"
  uid: c19fa2a0-5aee-4ef9-9b1f-c2e2f612ed3c
spec:
  clusterIP: 10.103.154.114
  clusterIPs:
  - 10.103.154.114
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31103
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: nginx-deploy
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
