apiVersion: v1
kind: Service
metadata:
  name: blue-service
  labels:
    app: blue-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    role: blue
  type: LoadBalancer
