apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: services-demo
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: # TODO: Add nodePort value
    protocol: TCP
