apiVersion: v1
kind: Service
metadata:
  name: green-service
  labels:
    app: green-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    role: green
  type: LoadBalancer
